blocked-faction-ids:
  - "-3"
  - "-2"
  - "-1"

settings:

blueprint-item:
  type: PAPER
  name: "&5{name} Blueprint"
  lore:
    - "&7Place this item to start"
    - "&7Generating a structure."
    - ""
    - "&7Direction: &9{direction}"

confirm-gui:
  title: "Click to Confirm"
  items:
    confirm:
      type: LIME_CONCRETE
      name: "&a&lCONFIRM"
      lore:
        - "&7Click to confirm"
    cancel:
      type: RED_CONCRETE
      name: "&c&lCANCEL"
      lore:
        - "&7Click to cancel"

rotate-gui:
  title: "{name} Placement"
  items:
    rotate-left:
      type: COMPASS
      name: "&5{name} Blueprint"
      lore:
        - "&7Rotate the blueprint left"
        - "&7by clicking this button"
        - " "
        - "&7New Direction: &9{direction}"
    rotate-right:
      type: COMPASS
      name: "&5{name} Blueprint"
      lore:
        - "&7Rotate the blueprint right"
        - "&7by clicking this button"
        - " "
        - "&7New Direction: &9{direction}"